openapi: 3.0.3
info:
  title: Carma
  version: 1.0.0
  contact: {}
servers:
  - url: https://apicarma-dev.bytequest.solutions/api/v1
tags:
  - name: Newsletter
    description: Subscription for Newsletter
paths:
  /newsletters:
    post:
      tags:
        - Newsletter
      operationId: Newsletter Subscription
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
              type: object
              properties:
                email:
                  type: string
                  example: John.Doe@gmail.com
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: You successfully subscribed to the newsletter.
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsletterSubscribeUnprocessableEntityError'
    get:
      tags:
        - Newsletter
      operationId: Newsletter Email List
      parameters:
        - name: page
          in: query
          description: Paginate Newsletters' email list , If you want to show the Next, Previous and Last Page's button you can use "Meta" section in the response
          schema:
            type: integer
          examples:
            example:
              value: 2
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/NewslettersData"
                  meta:
                    $ref: "#/components/schemas/PaginationMeta"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: You are not authorized
      security:
        - bearerAuth: []
components:
  schemas:
    NewsletterSubscribeUnprocessableEntityError:
      type: object
      properties:
        message:
          type: string
          example: Validation error occurred
        errors:
          type: array
          items:
            type: object
            properties:
              email:
                type: string
                example: The Email must be a valid email address
    NewslettersData:
      type: array
      items:
        type: object
        properties:
          Items:
            type: array
            items:
              type: object
              properties:
                ID:
                  type: string
                  example: c360beee-78d4-417a-8f73-8d1e25f76502
                Email:
                  type: string
                  example: John.Doe@gmail.com
    PaginationMeta:
      type: array
      items:
        type: object
        properties:
          totalItems:
            type: integer
            example: 221
          totalPages:
            type: integer
            example: 22
          current:
            type: integer
            example: 10
          next:
            type: integer
            example: 11
          previous:
            type: integer
            example: 9
          perPage:
            type: integer
            example: 10
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT